version: '3'

services:
  poe-openai-proxy:
    container_name: poe-openai-proxy
    image: caoyunzhou/poe-openai-proxy
    ports:
      - "8080:8080"
    environment:
      # 端口
      PORT: 8080
      # 多个令牌
      # TOKENS : mLMU8MMT21nfr0TGxN0i6A%3D%3D,token2,token3
      TOKENS : token1,token2,token3
      # 角色
      SIMULATE_ROLES : 2
      # 速率[默认为1分钟内每个令牌调用10个api]
      RATE_LIMIT : 10
      # 冷却令牌[#冷却几秒钟。同一个令牌在n秒内不能多次使用]
      COOL_DOWN : 10
      # 超时
      TIMEOUT : 60